import { Destination, Attraction } from '../types/travel';

export const DUBAI_ATTRACTIONS: Attraction[] = [
  {
    id: 'att-burj-khalifa',
    name: 'Burj Khalifa',
    city: 'Dubai',
    tag: 'Levels 124+125',
    description: "World's tallest skyscraper with breathtaking 360-degree observation decks.",
    startingPrice: 3950,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    duration: '2 Hours',
    openingHours: '08:30 AM – 11:00 PM',
    category: 'Architecture & Views',
    fastTrackAvailable: true,
  },
  {
    id: 'att-desert-safari',
    name: 'Desert Safari & BBQ',
    city: 'Dubai',
    tag: 'Adventure',
    description: 'Red dune bashing, camel rides, falconry showcase, and stargazing dinner camp.',
    startingPrice: 2800,
    image: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?auto=format&fit=crop&w=800&q=80',
    duration: '6 Hours (3 PM – 9 PM)',
    openingHours: 'Daily Afternoon Pickup',
    category: 'Desert Experience',
    fastTrackAvailable: true,
  },
  {
    id: 'att-museum-future',
    name: 'Museum of the Future',
    city: 'Dubai',
    tag: 'Must-Book Early',
    description: 'Architectural masterpiece exploring aerospace, ecology, and future human tech.',
    startingPrice: 3400,
    image: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=800&q=80',
    duration: '2.5 Hours',
    openingHours: '10:00 AM – 07:30 PM',
    category: 'Museum & Technology',
    fastTrackAvailable: false,
  },
  {
    id: 'att-marina-walk',
    name: 'Dubai Marina Walk',
    city: 'Dubai',
    tag: 'Leisure',
    description: '7km waterfront boulevard teeming with al fresco dining and evening dhow cruises.',
    startingPrice: 0,
    image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80',
    duration: 'Flexible Promenade',
    openingHours: 'Open 24 Hours',
    category: 'Waterfront & Promenade',
    fastTrackAvailable: false,
  },
  {
    id: 'att-miracle-garden',
    name: 'Miracle Garden',
    city: 'Dubai',
    tag: 'Seasonal Open',
    description: "The world's largest natural flower garden with over 150 million blooming blossoms.",
    startingPrice: 1900,
    image: 'https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=800&q=80',
    duration: '3 Hours',
    openingHours: '09:00 AM – 09:00 PM (Winter)',
    category: 'Botanical & Theme Park',
    fastTrackAvailable: true,
  },
];

export const MOCK_DESTINATIONS: Destination[] = [
  // ==========================================
  // 1. HIDDEN GEMS (10 DESTINATIONS)
  // ==========================================
  {
    id: 'dest-meghalaya',
    name: 'Meghalaya (Shillong & Cherrapunji)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'Abode of Clouds: bio-engineered living root bridges and crystal-clear Dawki river',
    image: 'https://images.unsplash.com/photo-1622308644420-a60965d143c6?auto=format&fit=crop&w=800&q=80',
    startingPrice: 21000,
    bestTimeToVisit: 'Sep – May',
    avgDuration: '5–6 Days',
    rating: 4.91,
    reviewsCount: 2200,
    popularActivities: ['Double Decker Living Root Bridge Trek', 'Dawki Umngot River Boating', 'Nohkalikai Waterfall Cliff View', 'Mawsmai Limestone Cave Walk'],
    description: 'Lush evergreen hills, cascading monster waterfalls, matrilineal tribal heritage, and the cleanest village in Asia.',
    weather: { temp: '19°C', condition: 'Misty & Refreshing', icon: 'water_drop', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Cash helpful for remote village treks and homestays.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa required.' },
    tags: ['Hidden Gems', 'Living Root Bridges', 'Offbeat', 'Waterfalls', 'Adventure'],
  },
  {
    id: 'dest-hampi',
    name: 'Hampi',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'UNESCO boulder kingdom: legendary Vijayanagara stone chariots and Tungabhadra sunsets',
    image: 'https://images.unsplash.com/photo-1600100397608-f010e47c1348?auto=format&fit=crop&w=800&q=80',
    startingPrice: 11500,
    bestTimeToVisit: 'Oct – Feb',
    avgDuration: '3–4 Days',
    rating: 4.9,
    reviewsCount: 2600,
    popularActivities: ['Vittala Temple Stone Chariot & Musical Pillars', 'Sunset over Matanga Hill Boulders', 'Tungabhadra Coracle Boat Ride', 'Virupaksha Temple Heritage Tour'],
    description: 'An open-air museum of colossal rock ruins, mythological landmarks, hippie island cafes, and mesmerizing golden hour landscapes.',
    weather: { temp: '28°C', condition: 'Sunny & Dry', icon: 'temple_hindu', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'UPI and cash for local guides and coracle boats.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa needed.' },
    tags: ['Hidden Gems', 'UNESCO Heritage', 'Architecture', 'Backpackers', 'Photography'],
  },
  {
    id: 'dest-lakshadweep',
    name: 'Lakshadweep Islands',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'Unspoiled coral atolls, glowing bioluminescent lagoons, and sea turtle havens',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    startingPrice: 32000,
    bestTimeToVisit: 'Oct – May',
    avgDuration: '5–6 Days',
    rating: 4.94,
    reviewsCount: 1600,
    popularActivities: ['Bangaram Island Coral Scuba Diving', 'Glass Bottom Lagoon Kayaking', 'Agatti Island Sunset Catamaran', 'Snorkeling with Sea Turtles & Rays'],
    description: 'India’s most pristine island sanctuary with turquoise waters matching the Maldives, zero commercial crowds, and thriving coral life.',
    weather: { temp: '29°C', condition: 'Tropical Sun', icon: 'scuba_diving', uvIndex: '7 High', seaTemp: '28°C' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'All package bookings handled via authorized portals.' },
    visaProtocol: { title: 'Lakshadweep Entry Permit', summary: 'Mandatory government permit arranged through registered tour operators.' },
    tags: ['Hidden Gems', 'Untouched Paradise', 'Coral Reefs', 'Scuba', 'Exclusive'],
  },
  {
    id: 'dest-spiti-valley',
    name: 'Spiti Valley (Kaza & Tabo)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'The Middle Land: thousand-year-old cliffside monasteries, Chandratal lake, and fossil villages',
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
    startingPrice: 24000,
    bestTimeToVisit: 'May – Oct',
    avgDuration: '6–8 Days',
    rating: 4.95,
    reviewsCount: 1780,
    popularActivities: ['Key Monastery 1,000-Year Murals & Chants', 'Chandratal Moon Lake Stargazing Camp', 'World Highest Post Office at Hikkim', 'Komic Village Highest Motorable Road'],
    description: 'Raw high-altitude desert surrounded by jagged snow ridges, Tibetan Buddhist stupas, and unforgettable starry night skies.',
    weather: { temp: '11°C', condition: 'Dry & Crisp Alpine', icon: 'landscape', uvIndex: '8 High' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Carry cash from Shimla/Manali as ATMs are rare in the valley.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'Standard ID.' },
    tags: ['Hidden Gems', 'High Altitude', 'Stargazing', 'Monasteries', 'Offbeat'],
  },
  {
    id: 'dest-ziro-valley',
    name: 'Ziro Valley & Tawang',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'Apatani paddy pine valleys, music festival grounds, and India’s largest Buddhist monastery',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    startingPrice: 26500,
    bestTimeToVisit: 'Sep – Apr',
    avgDuration: '6–7 Days',
    rating: 4.9,
    reviewsCount: 1420,
    popularActivities: ['Apatani Tribal Village Walk & Organic Farms', 'Tawang 400-Year Buddhist Monastery', 'Sela Pass Snow Frozen Lakes (13,700 ft)', 'Ziro Music Festival Grounds Trek'],
    description: 'Nestled in the lush hills of Arunachal Pradesh, Ziro showcases UNESCO-proposed sustainable tribal agriculture and serene mountain grandeur.',
    weather: { temp: '16°C', condition: 'Fresh Mountain Breeze', icon: 'park', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'UPI expanding; carry cash backup.' },
    visaProtocol: { title: 'Inner Line Permit (ILP)', summary: 'Online Arunachal ILP obtained in 24 hours.' },
    tags: ['Hidden Gems', 'Tribal Culture', 'Pine Valleys', 'Offbeat'],
  },
  {
    id: 'dest-kutch',
    name: 'Rann of Kutch (Gujarat)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'White salt desert under moonlight, Rann Utsav tent cities, and vibrant folk arts',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    startingPrice: 18000,
    bestTimeToVisit: 'Nov – Feb (Rann Utsav)',
    avgDuration: '3–4 Days',
    rating: 4.87,
    reviewsCount: 2300,
    popularActivities: ['Full Moon White Desert Camel Cart Ride', 'Kala Dungar Highest Hill Sunset', 'Rann Utsav Luxury Tent City Cultural Dances', 'Rogan Art & Kutchi Embroidery Villages'],
    description: 'An endless sea of white salt crystals that shines silver beneath full moon skies, accompanied by desert camp luxury and colorful handicrafts.',
    weather: { temp: '24°C', condition: 'Sunny Days, Crisp Desert Nights', icon: 'wb_twilight', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Cards & UPI in tent city.' },
    visaProtocol: { title: 'Rann Permit', summary: 'Online permit issued instantly at Bhirandiyara checkpoint.' },
    tags: ['Hidden Gems', 'Desert', 'Cultural Festival', 'Photography', 'Unique'],
  },
  {
    id: 'dest-coorg',
    name: 'Coorg (Kodagu)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Hidden Gems',
    tagline: 'The Scotland of India: lush coffee estates, spice trails, and misty waterfalls',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
    startingPrice: 12500,
    bestTimeToVisit: 'Oct – Mar',
    avgDuration: '3–4 Days',
    rating: 4.81,
    reviewsCount: 2900,
    popularActivities: ['Coffee Plantation Walking Tour & Tasting', 'Abbey & Iruppu Falls Visit', 'Bylakuppe Golden Temple Tibetan Monastery', 'Dubare Elephant Camp River Crossing'],
    description: 'Rolling green valleys of Karnataka packed with aromatic coffee blossoms, rich Kodava hospitality, homestays, and pristine western ghats.',
    weather: { temp: '22°C', condition: 'Cool & Fragrant', icon: 'eco', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Standard Indian digital payments.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa required.' },
    tags: ['Hidden Gems', 'Coffee Estates', 'Nature', 'Couples', 'Relaxed'],
  },
  {
    id: 'dest-cappadocia',
    name: 'Cappadocia (Turkey)',
    stateOrCountry: 'Turkey',
    isInternational: true,
    category: 'Hidden Gems',
    tagline: 'Fairy chimneys, cave suites carved into cliffs, and 150 hot air balloons at sunrise',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80',
    startingPrice: 65000,
    bestTimeToVisit: 'Apr – Jun & Sep – Nov',
    avgDuration: '4–5 Days',
    rating: 4.95,
    reviewsCount: 3200,
    popularActivities: ['Sunrise Hot Air Balloon Flight over Rose Valley', 'Stay in a 500-Year Authentic Cave Suite', 'Derinkuyu Underground Multi-Level City', 'Goreme Open Air Museum Rock Frescoes'],
    description: 'Otherworldly rock formations, troglodyte cave architecture, vibrant ceramic workshops, and breathtaking sunrise balloon launches.',
    weather: { temp: '20°C', condition: 'Sunny & Crisp Valley', icon: 'flight', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'TRY (Turkish Lira)', rateText: '1 TRY ≈ ₹2.4', note: 'Forex cards widely accepted.' },
    visaProtocol: { title: 'eVisa for Indians', summary: 'Instant eVisa with valid US, UK, or Schengen visa.' },
    tags: ['Hidden Gems', 'Hot Air Balloons', 'Cave Hotels', 'Photography'],
  },
  {
    id: 'dest-georgia-baku',
    name: 'Georgia (Tbilisi & Kazbegi)',
    stateOrCountry: 'Georgia (Caucasus)',
    isInternational: true,
    category: 'Hidden Gems',
    tagline: 'Ancient Silk Road castles, cliffside Gergeti church, and Caucasus mountain peaks',
    image: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=800&q=80',
    startingPrice: 46000,
    bestTimeToVisit: 'Apr – Jun & Sep – Oct',
    avgDuration: '5–6 Days',
    rating: 4.87,
    reviewsCount: 2100,
    popularActivities: ['Kazbegi Mount Gergeti Trinity Church Peak', 'Tbilisi Sulfur Baths & Narikala Fortress Cable Car', 'Gudauri Friendship Monument Viewpoint', 'Traditional Khachapuri & Wine Tasting'],
    description: 'European flair at budget-friendly rates: cobblestone streets, lush mountain ranges, and hospitable wine traditions.',
    weather: { temp: '20°C', condition: 'Sunny & Mountain Breeze', icon: 'landscape', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'GEL (Georgian Lari)', rateText: '1 GEL ≈ ₹31.5', note: 'Cards accepted in cities.' },
    visaProtocol: { title: 'Online eVisa', summary: 'Fast 3-day online eVisa issuance for Indian travelers.' },
    tags: ['Hidden Gems', 'European Feel', 'Mountain Drives', 'Short Flight'],
  },
  {
    id: 'dest-hallstatt',
    name: 'Hallstatt & Salzkammergut',
    stateOrCountry: 'Austria',
    isInternational: true,
    category: 'Hidden Gems',
    tagline: 'Storybook lakeside village nestled between alpine cliffs and 7,000-year salt mines',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    startingPrice: 112000,
    bestTimeToVisit: 'May – Oct & Dec (Winter fairytale)',
    avgDuration: '4–5 Days',
    rating: 4.96,
    reviewsCount: 1890,
    popularActivities: ['Hallstatt Lake Wooden Boat Serenade', 'World Oldest Salt Mine Funicular & Slide', 'Skywalk 360-Degree Panorama Platform', 'Five Fingers Mountain Observation Platform'],
    description: 'Often called the most picturesque lake village on earth, featuring 16th-century Alpine houses reflected in glass-calm waters.',
    weather: { temp: '17°C', condition: 'Fresh Alpine Air', icon: 'cabin', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Forex cards supported universally.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Standard tourist Schengen visa application.' },
    tags: ['Hidden Gems', 'Alpine Village', 'Lakeside', 'Storybook'],
  },

  // ==========================================
  // 2. EUROPEAN WONDERS (10 DESTINATIONS)
  // ==========================================
  {
    id: 'dest-switzerland',
    name: 'Switzerland (Zurich & Interlaken)',
    stateOrCountry: 'Switzerland',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Snow-capped alpine giants, Glacier Express trains, and crystal mountain lakes',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    startingPrice: 125000,
    bestTimeToVisit: 'Jun – Sep (Summer) & Dec – Mar (Ski)',
    avgDuration: '7–8 Days',
    rating: 4.97,
    reviewsCount: 2800,
    popularActivities: ['Jungfraujoch Top of Europe Mountain Rail', 'Mount Titlis Rotating Rotair & Cliff Walk', 'Lake Brienz & Thun Turquoise Boat Cruise', 'Matterhorn Zermatt Alpine Panorama'],
    description: 'The fairy-tale jewel of Europe with clockwork trains, fondue feasts, cascading waterfalls in Lauterbrunnen, and legendary alpine peaks.',
    weather: { temp: '16°C', condition: 'Crisp Mountain Breeze', icon: 'ac_unit', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'CHF (Swiss Franc)', rateText: '1 CHF ≈ ₹96.5', note: 'Contactless payments accepted everywhere from cable cars to summit cafes.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Standard Schengen tourist visa; TRAVELAI provides verified flight/hotel itinerary vouchers.' },
    tags: ['European Wonders', 'Scenic Trains', 'Snow & Alps', 'Bucket List', 'Luxury'],
  },
  {
    id: 'dest-paris',
    name: 'Paris & France',
    stateOrCountry: 'France',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'City of Light: Eiffel Tower sparkle, Louvre treasures, and Seine champagne cruises',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    startingPrice: 98000,
    bestTimeToVisit: 'Apr – Oct',
    avgDuration: '5–6 Days',
    rating: 4.91,
    reviewsCount: 4500,
    popularActivities: ['Eiffel Tower Summit Skip-the-Line', 'Louvre Museum Mona Lisa Highlights', 'Seine River Sunset Illumination Cruise', 'Palace of Versailles Hall of Mirrors'],
    description: 'Romantic boulevards, world-class gastronomy, timeless haute couture, and peerless artistic heritage.',
    weather: { temp: '18°C', condition: 'Mild & Romantic', icon: 'wb_sunny', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Contactless cards work across Metro and bistros.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'French embassy Schengen visa processing.' },
    tags: ['European Wonders', 'Romance', 'Museums & Art', 'Architecture', 'Culinary'],
  },
  {
    id: 'dest-italy',
    name: 'Italy (Rome, Florence & Venice)',
    stateOrCountry: 'Italy',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Colosseum gladiators, Vatican masterpieces, and romantic Grand Canal gondolas',
    image: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=800&q=80',
    startingPrice: 105000,
    bestTimeToVisit: 'Apr – Jun & Sep – Oct',
    avgDuration: '7–8 Days',
    rating: 4.93,
    reviewsCount: 3900,
    popularActivities: ['Colosseum & Roman Forum VIP Underground', 'Vatican City & Sistine Chapel', 'Venice Grand Canal Gondola Serenade', 'Florence Uffizi Gallery & Duomo Dome Climb'],
    description: 'An open-air living museum where every corner reveals Renaissance treasures, handcrafted pasta, espresso bars, and iconic cobblestone piazzas.',
    weather: { temp: '22°C', condition: 'Sunny Mediterranean', icon: 'wb_sunny', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Forex cards supported universally.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Standard tourist Schengen visa application.' },
    tags: ['European Wonders', 'History', 'Art & Culture', 'Wine & Gastronomy', 'Romantic'],
  },
  {
    id: 'dest-london-uk',
    name: 'United Kingdom (London & Scotland)',
    stateOrCountry: 'United Kingdom',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Big Ben, Buckingham Palace pomp, London Eye views, and misty Scottish Highlands',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    startingPrice: 115000,
    bestTimeToVisit: 'May – Sep',
    avgDuration: '6–8 Days',
    rating: 4.89,
    reviewsCount: 4100,
    popularActivities: ['Tower of London & Crown Jewels', 'London Eye Sunset Private Capsule', 'Edinburgh Castle & Royal Mile Walk', 'Loch Ness & Scottish Highlands Day Tour'],
    description: 'Royal palaces, West End theatrical blockbusters, double-decker buses, world-class free museums, and dramatic Scottish lochs.',
    weather: { temp: '18°C', condition: 'Mild with Occasional Drizzle', icon: 'cloud', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'GBP (£)', rateText: '1 GBP ≈ ₹109', note: 'Card-only environment across London Underground and black cabs.' },
    visaProtocol: { title: 'UK Standard Visitor Visa', summary: '6-month multi-entry visitor visa processed through VFS Global.' },
    tags: ['European Wonders', 'Royal Heritage', 'Museums', 'Theatre', 'Castles'],
  },
  {
    id: 'dest-greece',
    name: 'Greece (Santorini & Athens)',
    stateOrCountry: 'Greece',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Whitewashed Aegean caldera cliffs, blue-domed churches, and the ancient Parthenon',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    startingPrice: 118000,
    bestTimeToVisit: 'May – Oct',
    avgDuration: '6–8 Days',
    rating: 4.94,
    reviewsCount: 3100,
    popularActivities: ['Santorini Oia Sunset Caldera Walk', 'Catamaran Cruise to Red Beach & Hot Springs', 'Acropolis & Parthenon Ancient Citadel Tour', 'Mykonos Windmills & Little Venice Beach Clubs'],
    description: 'Iconic cobalt-blue and pure-white cliffside architecture, Greek feta and olive groves, breathtaking Mediterranean sunsets, and mythical ruins.',
    weather: { temp: '25°C', condition: 'Sunny Aegean Skies', icon: 'wb_sunny', uvIndex: '6 Moderate', seaTemp: '24°C' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Cards accepted across islands.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Standard tourist Schengen visa required.' },
    tags: ['European Wonders', 'Santorini Sunset', 'Honeymoon', 'Islands', 'Ancient Ruins'],
  },
  {
    id: 'dest-iceland',
    name: 'Iceland (Reykjavik & Golden Circle)',
    stateOrCountry: 'Iceland',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Land of Fire & Ice: dancing Aurora Borealis, geothermal Blue Lagoon, and thundering waterfalls',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
    startingPrice: 145000,
    bestTimeToVisit: 'Sep – Mar (Northern Lights) & Jun – Aug (Midnight Sun)',
    avgDuration: '7–8 Days',
    rating: 4.97,
    reviewsCount: 1950,
    popularActivities: ['Northern Lights Aurora Superjeep Hunt', 'Blue Lagoon Geothermal Mineral Soak', 'Golden Circle (Geysir, Gullfoss, Thingvellir)', 'Jökulsárlón Glacier Lagoon Iceberg Zodiac'],
    description: 'Black sand volcanic beaches, colossal ice caves, spouting geysers, and otherworldly celestial night skies.',
    weather: { temp: '4°C', condition: 'Crisp Arctic Wonder', icon: 'ac_unit', uvIndex: '2 Low' },
    currencyInfo: { currencyName: 'ISK (Icelandic Króna)', rateText: '100 ISK ≈ ₹61', note: 'Entire country operates 100% cashless.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Apply via Embassy of Iceland or Denmark in India.' },
    tags: ['European Wonders', 'Northern Lights', 'Geothermal Spas', 'Bucket List'],
  },
  {
    id: 'dest-spain',
    name: 'Spain (Barcelona & Madrid)',
    stateOrCountry: 'Spain',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Gaudí’s Sagrada Família, lively tapas crawl, flamenco rhythms, and Mediterranean beaches',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80',
    startingPrice: 94000,
    bestTimeToVisit: 'Apr – Jun & Sep – Nov',
    avgDuration: '6–7 Days',
    rating: 4.9,
    reviewsCount: 3300,
    popularActivities: ['Sagrada Família & Park Güell Gaudí Marvels', 'Barceloneta Beach Sunset & Paella Lunch', 'Prado Museum Masterpieces in Madrid', 'Authentic Andalusian Flamenco Night Show'],
    description: 'Vibrant plazas buzzing until late at night, astonishing modernist architecture, sunny Mediterranean shores, and delicious tapas.',
    weather: { temp: '23°C', condition: 'Warm & Sunny', icon: 'wb_sunny', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Forex cards supported universally.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Spanish Schengen tourist visa.' },
    tags: ['European Wonders', 'Architecture', 'Tapas & Food', 'Nightlife', 'Beaches'],
  },
  {
    id: 'dest-amsterdam',
    name: 'Amsterdam & Netherlands',
    stateOrCountry: 'Netherlands',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Canal cruises, Van Gogh masterpieces, iconic windmills, and springtime Keukenhof tulips',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=800&q=80',
    startingPrice: 92000,
    bestTimeToVisit: 'Apr – Oct (Tulips in Apr–May)',
    avgDuration: '5–6 Days',
    rating: 4.89,
    reviewsCount: 2900,
    popularActivities: ['Herengracht Historic Canal Cruise with Dutch Cheese', 'Van Gogh Museum & Rijksmuseum Tour', 'Zaanse Schans Windmills & Clog Workshop', 'Keukenhof 7-Million Tulip Garden Excursion'],
    description: 'Charming gabled townhouses leaning over 17th-century canals, bicycle avenues, world-class art, and laid-back cafe culture.',
    weather: { temp: '16°C', condition: 'Pleasant & Breezy', icon: 'directions_bike', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Contactless cards only on public transit.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Netherlands Schengen visa.' },
    tags: ['European Wonders', 'Canals', 'Museums', 'Tulips', 'Cycling'],
  },
  {
    id: 'dest-norway',
    name: 'Norway (Oslo & Bergen Fjords)',
    stateOrCountry: 'Norway',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Deep emerald UNESCO fjords, Flåm scenic railway, and midnight sun serenity',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    startingPrice: 138000,
    bestTimeToVisit: 'Jun – Aug (Fjords) & Nov – Mar (Auroras)',
    avgDuration: '7–8 Days',
    rating: 4.96,
    reviewsCount: 1680,
    popularActivities: ['Nærøyfjord Electric Silent Catamaran Cruise', 'Flåm Mountain Railway Journey', 'Bryggen UNESCO Wharf in Bergen', 'Tromsø Reindeer Sledding & Aurora Camp'],
    description: 'Dramatic vertical mountains tumbling straight into pristine saltwater fiords, cascading glaciers, and cleanest air in the world.',
    weather: { temp: '15°C', condition: 'Cool Fjord Air', icon: 'sailing', uvIndex: '3 Mild' },
    currencyInfo: { currencyName: 'NOK (Norwegian Krone)', rateText: '100 NOK ≈ ₹78', note: 'Completely cashless.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Norwegian embassy Schengen visa.' },
    tags: ['European Wonders', 'Fjords', 'Scenic Trains', 'Pristine Nature'],
  },
  {
    id: 'dest-vienna',
    name: 'Vienna & Salzburg (Austria)',
    stateOrCountry: 'Austria',
    isInternational: true,
    category: 'European Wonders',
    tagline: 'Imperial Habsburg palaces, Sound of Music valleys, and classical Mozart concerts',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
    startingPrice: 108000,
    bestTimeToVisit: 'May – Sep & Dec (Christmas Markets)',
    avgDuration: '6–7 Days',
    rating: 4.92,
    reviewsCount: 2400,
    popularActivities: ['Schönbrunn Palace Imperial Grand Tour', 'St. Stephen’s Cathedral & Ringstrasse Stroll', 'Salzburg Mirabell Gardens & Fortress', 'Classical Orchestra Concert at Musikverein'],
    description: 'Grand baroque architecture, elegant coffeehouse culture with Sachertorte chocolate cake, and sublime alpine scenery.',
    weather: { temp: '19°C', condition: 'Sunny & Pleasant', icon: 'theater_comedy', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'EUR (€)', rateText: '1 EUR ≈ ₹92.8', note: 'Forex cards supported universally.' },
    visaProtocol: { title: 'Schengen Visa', summary: 'Austrian Schengen visa.' },
    tags: ['European Wonders', 'Classical Music', 'Imperial Palaces', 'Culture'],
  },

  // ==========================================
  // 3. SOUTH EAST ASIAN ESCAPES (9 DESTINATIONS)
  // ==========================================
  {
    id: 'dest-bali',
    name: 'Bali',
    stateOrCountry: 'Indonesia',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Emerald terraced rice fields, sacred water temples, and private pool villas',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    startingPrice: 42000,
    bestTimeToVisit: 'Apr – Oct & Nov',
    avgDuration: '6–7 Days',
    rating: 4.9,
    reviewsCount: 3890,
    popularActivities: ['Tegalalang Rice Terraces Swing', 'Uluwatu Clifftop Temple & Kecak Dance', 'Nusa Penida Kelingking Beach Tour', 'Jimbaran Candlelit Seafood Feast'],
    description: 'The Island of the Gods offers spiritual sanctuaries, surf-washed beaches, artisan workshops, and secluded jungle retreats.',
    weather: { temp: '29°C', condition: 'Tropical Warm', icon: 'wb_sunny', uvIndex: '7 High' },
    currencyInfo: { currencyName: 'IDR (Indonesian Rupiah)', rateText: '10,000 IDR ≈ ₹54', note: 'Multi-currency forex cards recommended for dining & beach clubs.' },
    visaProtocol: { title: 'Visa on Arrival (VoA)', summary: '30-day VoA available online or on arrival at DPS airport for Indians (~$35).' },
    tags: ['South East Asian Escapes', 'Tropical', 'Honeymoon', 'Villas', 'Culture'],
  },
  {
    id: 'dest-singapore',
    name: 'Singapore',
    stateOrCountry: 'Singapore',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'A garden city of the future: botanical wonderlands, mega theme parks, and Michelin street food',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
    startingPrice: 48000,
    bestTimeToVisit: 'Year Round (Nov-Jan festive)',
    avgDuration: '5–6 Days',
    rating: 4.9,
    reviewsCount: 3400,
    popularActivities: ['Supertree Grove Light & Sound Show', 'Universal Studios Singapore Rides', 'Marina Bay Sands Infinity Observation', 'Sentosa Skyline Luge & Cable Car'],
    description: 'Immaculate urban engineering meets lush botanical architecture, sensational dining, and safe entertainment for travelers of all ages.',
    weather: { temp: '30°C', condition: 'Warm with Occasional Showers', icon: 'sunny', uvIndex: '8 High' },
    currencyInfo: { currencyName: 'SGD (Singapore Dollar)', rateText: '1 SGD ≈ ₹64.5', note: 'Tap to pay on MRT subway trains with any contactless forex card.' },
    visaProtocol: { title: 'Electronic Visa (e-Visa)', summary: 'Applied via authorized visa agents, approved in 3-4 working days.' },
    tags: ['South East Asian Escapes', 'Family Fun', 'Theme Parks', 'Future City', 'Gastronomy'],
  },
  {
    id: 'dest-thailand',
    name: 'Thailand (Bangkok & Phuket)',
    stateOrCountry: 'Thailand',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Golden Buddhist temples, floating markets, limestone islands, and energetic nightlife',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80',
    startingPrice: 32000,
    bestTimeToVisit: 'Nov – Apr',
    avgDuration: '5–7 Days',
    rating: 4.88,
    reviewsCount: 6200,
    popularActivities: ['Phi Phi & Maya Bay Speedboat Tour', 'Grand Palace & Wat Pho Giant Reclining Buddha', 'Chao Phraya Dinner Cruise', 'James Bond Island Sea Canoeing'],
    description: 'The Land of Smiles provides sensational street food, world-famous island hopping, vibrant shopping night markets, and warm Thai massages.',
    weather: { temp: '31°C', condition: 'Sunny & Tropical', icon: 'wb_sunny', uvIndex: '8 High', seaTemp: '29°C' },
    currencyInfo: { currencyName: 'THB (Thai Baht)', rateText: '1 THB ≈ ₹2.35', note: 'Very budget friendly. Cash or forex cards widely used.' },
    visaProtocol: { title: 'Visa-Free Entry', summary: 'Visa-free entry currently available for Indian tourists (up to 60 days).' },
    tags: ['South East Asian Escapes', 'Islands', 'Beaches', 'Nightlife', 'Budget Friendly'],
  },
  {
    id: 'dest-maldives',
    name: 'Maldives',
    stateOrCountry: 'Maldives',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Pure romance: private overwater bungalows, neon lagoons, and vibrant manta rays',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    startingPrice: 68000,
    bestTimeToVisit: 'Nov – Apr',
    avgDuration: '4–5 Days',
    rating: 4.96,
    reviewsCount: 3100,
    popularActivities: ['Overwater Villa Sunset Plunge Pool', 'Manta Ray & Whale Shark Snorkeling', 'Undersea Restaurant Dining Experience', 'Private Sandbank Champagne Picnic'],
    description: 'The world’s benchmark for tropical luxury. Wake up to direct ocean access, glowing bioluminescent waves, and five-star culinary luxury.',
    weather: { temp: '29°C', condition: 'Tropical Blue Skies', icon: 'pool', uvIndex: '8 High', seaTemp: '28°C' },
    currencyInfo: { currencyName: 'USD ($) / MVR', rateText: '1 USD ≈ ₹86.5', note: 'Resorts bill in USD; cards accepted universally.' },
    visaProtocol: { title: 'Free Visa on Arrival', summary: 'Complimentary 30-day tourist visa granted upon arrival with hotel confirmation.' },
    tags: ['South East Asian Escapes', 'Honeymoon', 'Ultra Luxury', 'Overwater Villas', 'Marine'],
  },
  {
    id: 'dest-malaysia',
    name: 'Malaysia (Kuala Lumpur & Langkawi)',
    stateOrCountry: 'Malaysia',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Petronas Twin Towers, duty-free island beaches, and ancient rainforest cable cars',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=800&q=80',
    startingPrice: 34500,
    bestTimeToVisit: 'Year Round (Nov-Mar Langkawi peak)',
    avgDuration: '5–6 Days',
    rating: 4.84,
    reviewsCount: 3900,
    popularActivities: ['Petronas Skybridge & Observation Deck', 'Batu Caves Rainbow Steps & Lord Murugan Statue', 'Langkawi SkyCab & Curved Suspension Bridge', 'Jalan Alor Night Food Street Extravaganza'],
    description: 'Truly Asia: multicultural culinary bliss, soaring skyline skyscrapers, duty-free beaches, and ancient geoforest parks.',
    weather: { temp: '30°C', condition: 'Warm & Tropical', icon: 'sunny', uvIndex: '7 High' },
    currencyInfo: { currencyName: 'MYR (Malaysian Ringgit)', rateText: '1 MYR ≈ ₹19.2', note: 'Cards accepted across shopping malls and transport apps.' },
    visaProtocol: { title: 'Visa-Free Travel', summary: 'Visa-free entry available for Indian passport holders (30 days).' },
    tags: ['South East Asian Escapes', 'Family', 'Shopping', 'Beaches', 'Direct Flights'],
  },
  {
    id: 'dest-vietnam',
    name: 'Vietnam (Hanoi, Da Nang & Ha Long)',
    stateOrCountry: 'Vietnam',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Emerald Ha Long Bay islands, Golden Hand Bridge, and mouthwatering Pho',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
    startingPrice: 38000,
    bestTimeToVisit: 'Oct – Apr',
    avgDuration: '6–7 Days',
    rating: 4.91,
    reviewsCount: 3800,
    popularActivities: ['Ha Long Bay Luxury Overnight Cruise & Kayaking', 'Ba Na Hills Golden Bridge in Giant Hands', 'Hoi An Ancient Town Lantern River Boat', 'Hanoi Old Quarter Street Food & Egg Coffee'],
    description: 'Tremendous value for Indian travelers: limestone karst peaks rising from mist, French colonial architecture, tailor-made suits, and delicious culinary diversity.',
    weather: { temp: '25°C', condition: 'Pleasant & Warm', icon: 'wb_sunny', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'VND (Vietnamese Dong)', rateText: '100,000 VND ≈ ₹340', note: 'Incredible purchasing power. Cash and cards both useful.' },
    visaProtocol: { title: '30-Day Online eVisa', summary: 'Applied directly on government portal for ~$25 with 3-day approval.' },
    tags: ['South East Asian Escapes', 'Value for Money', 'Cruises', 'Food & Coffee', 'Culture'],
  },
  {
    id: 'dest-philippines',
    name: 'Philippines (Boracay & El Nido)',
    stateOrCountry: 'Philippines',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Powder-soft White Beach, hidden lagoons, and limestone karst boat expeditions',
    image: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=800&q=80',
    startingPrice: 49000,
    bestTimeToVisit: 'Nov – May',
    avgDuration: '6–7 Days',
    rating: 4.92,
    reviewsCount: 2250,
    popularActivities: ['El Nido Island Hopping Tour A (Big Lagoon Kayak)', 'Boracay White Beach Sunset Paraw Sailing', 'Secret Beach Swimming through Rock Crevice', 'Scuba Diving at Tubbataha Reefs'],
    description: '7,000+ islands of turquoise brilliance: world-famous diving, paddle-boarding through hidden cave holes, and sunset fire dances.',
    weather: { temp: '30°C', condition: 'Tropical Sun & Surf', icon: 'pool', uvIndex: '8 High', seaTemp: '28°C' },
    currencyInfo: { currencyName: 'PHP (Philippine Peso)', rateText: '1 PHP ≈ ₹1.5', note: 'ATMs in tourist hubs; cash preferred on remote islands.' },
    visaProtocol: { title: 'Philippine e-Visa', summary: 'Online tourist visa processing.' },
    tags: ['South East Asian Escapes', 'Beaches', 'Island Hopping', 'Kayaking', 'Marine'],
  },
  {
    id: 'dest-cambodia',
    name: 'Cambodia (Siem Reap & Angkor)',
    stateOrCountry: 'Cambodia',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Sunrise over Angkor Wat, giant banyan root temples of Ta Prohm, and Tonle Sap lake',
    image: 'https://images.unsplash.com/photo-1600100397608-f010e47c1348?auto=format&fit=crop&w=800&q=80',
    startingPrice: 36000,
    bestTimeToVisit: 'Nov – Mar',
    avgDuration: '4–5 Days',
    rating: 4.88,
    reviewsCount: 2400,
    popularActivities: ['Angkor Wat Reflection Pool 5:00 AM Sunrise', 'Ta Prohm Tomb Raider Giant Root Temple', 'Bayon Temple 216 Smiling Stone Faces', 'Tonle Sap Floating Fishermen Village Cruise'],
    description: 'The monumental legacy of the Khmer Empire: ancient stone sanctuaries engulfed by jungle canopies, tuk-tuk rides, and warm hospitality.',
    weather: { temp: '29°C', condition: 'Warm & Tropical', icon: 'temple_buddhist', uvIndex: '7 High' },
    currencyInfo: { currencyName: 'USD ($) / KHR', rateText: '1 USD ≈ ₹86.5', note: 'USD used seamlessly for all tourist transactions.' },
    visaProtocol: { title: 'Instant eVisa / VoA', summary: 'Available online or on arrival at REP airport for $30.' },
    tags: ['South East Asian Escapes', 'Ancient Temples', 'Khmer Culture', 'History'],
  },
  {
    id: 'dest-srilanka',
    name: 'Sri Lanka (Sigiriya & Ella)',
    stateOrCountry: 'Sri Lanka',
    isInternational: true,
    category: 'South East Asian Escapes',
    tagline: 'Sigiriya Rock Fortress, scenic blue tea trains of Ella, and golden palm beaches',
    image: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
    startingPrice: 28500,
    bestTimeToVisit: 'Dec – Apr (South & West coasts)',
    avgDuration: '5–6 Days',
    rating: 4.86,
    reviewsCount: 3400,
    popularActivities: ['Climbing Sigiriya Lion Rock Fortress', 'Kandy to Ella Blue Scenic Train Journey', 'Mirissa Blue Whale Watching Safari', 'Pinnawala Elephant Orphanage Feeding'],
    description: 'The pearl of the Indian Ocean right at India’s doorstep: Ramayana trails, mist-wrapped tea hills, wildlife safaris with leopards, and warm surf breaks.',
    weather: { temp: '29°C', condition: 'Tropical Sun', icon: 'train', uvIndex: '7 High' },
    currencyInfo: { currencyName: 'LKR (Sri Lankan Rupee)', rateText: '1 LKR ≈ ₹0.29', note: 'Extremely cost effective for dining and luxury hotels.' },
    visaProtocol: { title: 'Free ETA Visa', summary: 'Free Electronic Travel Authorization for Indian tourists.' },
    tags: ['South East Asian Escapes', 'Close to India', 'Budget Friendly', 'Wildlife', 'Scenic Train'],
  },

  // ==========================================
  // 4. DOMESTIC HAVENS (10 DESTINATIONS)
  // ==========================================
  {
    id: 'dest-goa',
    name: 'Goa',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Sun-drenched beaches, Portuguese villas, beach clubs, and coastal seafood',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    startingPrice: 14500,
    bestTimeToVisit: 'Oct – Mar',
    avgDuration: '4–5 Days',
    rating: 4.8,
    reviewsCount: 5600,
    popularActivities: ['Anjuna Beach Sunset Cafes', 'Water Sports at Calangute', 'Old Goa Basilica & Heritage Walk', 'Mandovi River Catamaran Cruise'],
    description: 'India’s ultimate beach sanctuary blending laid-back susegad lifestyle, Portuguese colonial architecture, electric nightlife, and serene spice plantations.',
    weather: { temp: '30°C', condition: 'Tropical Breeze', icon: 'sunny', uvIndex: '6 Moderate', seaTemp: '28°C' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'UPI QR accepted seamlessly across street shacks and luxury resorts.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa required. Standard government photo ID needed for flights.' },
    tags: ['Domestic Havens', 'Beaches', 'Nightlife', 'Seafood', 'Heritage'],
  },
  {
    id: 'dest-kerala',
    name: 'Kerala',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: "God's Own Country: tranquil palm backwaters, misty tea valleys, and ayurveda",
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    startingPrice: 18500,
    bestTimeToVisit: 'Sep – Mar',
    avgDuration: '5–6 Days',
    rating: 4.9,
    reviewsCount: 4210,
    popularActivities: ['Alleppey Private Houseboat Cruise', 'Munnar Tea Plantation Treks', 'Periyar Wildlife Sanctuary Boating', 'Ayurvedic Rejuvenation Massages'],
    description: 'Soak in the soothing calm of backwater lagoons, spice-scented hills, coastal heritage in Fort Kochi, and authentic Kathakali performances.',
    weather: { temp: '27°C', condition: 'Pleasant & Cool in Hills', icon: 'thermostat', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Full digital payment connectivity throughout Kerala.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa needed. Valid Gov ID required.' },
    tags: ['Domestic Havens', 'Nature', 'Relaxation', 'Houseboats', 'Ayurveda'],
  },
  {
    id: 'dest-kashmir',
    name: 'Kashmir (Srinagar & Gulmarg)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Paradise on Earth: floating shikaras, snow-capped peaks, and pine valleys',
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
    startingPrice: 22000,
    bestTimeToVisit: 'Apr – Oct (Snow in Dec–Feb)',
    avgDuration: '5–6 Days',
    rating: 4.95,
    reviewsCount: 3800,
    popularActivities: ['Dal Lake Sunset Shikara Ride', 'Gulmarg Gondola to Apharwat Peak', 'Pahalgam Aru & Betaab Valley', 'Mughal Gardens Heritage Walk'],
    description: 'Fabled valleys of alpine grandeur, hand-carved cedar houseboats on Nigeen Lake, crisp mountain air, and authentic Kashmiri saffron and walnuts.',
    weather: { temp: '16°C', condition: 'Crisp & Sunny', icon: 'ac_unit', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Prepaid mobile networks require local post-paid SIMs.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No permit for general areas. Valid photo ID needed.' },
    tags: ['Domestic Havens', 'Snow & Mountains', 'Honeymoon', 'Nature', 'Heritage'],
  },
  {
    id: 'dest-rajasthan-jaipur-udaipur',
    name: 'Jaipur & Udaipur (Rajasthan)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Land of Maharajas: glittering lake palaces, golden forts, and royal hospitality',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    startingPrice: 19500,
    bestTimeToVisit: 'Oct – Mar',
    avgDuration: '5–6 Days',
    rating: 4.88,
    reviewsCount: 4600,
    popularActivities: ['Amber Fort Elephant Walk', 'Lake Pichola Sunset Boat Cruise', 'City Palace & Hawa Mahal Tour', 'Chokhi Dhani Rajasthani Cultural Dinner'],
    description: 'Step into legendary royal dynasties with opulent marble palaces, desert sunsets, colorful bazaars, and world-renowned Rajasthani hospitality.',
    weather: { temp: '26°C', condition: 'Warm & Dry', icon: 'wb_sunny', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'UPI and credit cards widely accepted across forts and boutique hotels.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'Standard ID check for domestic flights.' },
    tags: ['Domestic Havens', 'Royal Palaces', 'Heritage', 'Culture', 'Photography'],
  },
  {
    id: 'dest-andaman',
    name: 'Andaman & Nicobar Islands',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Crystal turquoise seas, Radhanagar white sands, and vibrant coral reefs',
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    startingPrice: 28000,
    bestTimeToVisit: 'Nov – May',
    avgDuration: '5–7 Days',
    rating: 4.9,
    reviewsCount: 2900,
    popularActivities: ['Scuba Diving at Elephant Beach', 'Radhanagar Sunset Leisure', 'Cellular Jail Light & Sound Show', 'Sea Karting & Glass Bottom Boats'],
    description: 'An idyllic tropical archipelago offering Asia’s best white sand beaches, untouched tropical rainforests, and world-class scuba diving sites.',
    weather: { temp: '29°C', condition: 'Tropical Warm', icon: 'water', uvIndex: '7 High', seaTemp: '28°C' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Carry cash backup for boat rides and remote island cafes.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa needed for Indian citizens. Restricted area permits for foreign nationals.' },
    tags: ['Domestic Havens', 'Beaches', 'Scuba Diving', 'Islands', 'Honeymoon'],
  },
  {
    id: 'dest-himachal',
    name: 'Manali & Shimla (Himachal)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Colonial hill stations, snowy Rohtang passes, and pine river valleys',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    startingPrice: 15500,
    bestTimeToVisit: 'All Year (Snow Dec–Feb, Pleasurable May–Jun)',
    avgDuration: '5–6 Days',
    rating: 4.82,
    reviewsCount: 5200,
    popularActivities: ['Solang Valley Paragliding & Ziplining', 'Rohtang Pass Snow Point', 'Shimla Mall Road & Ridge Stroll', 'Jogini Waterfall Trek'],
    description: 'Breath-taking Himalayan escapes featuring colonial mountain railways, apple orchards, rushing rivers for white water rafting, and snow playgrounds.',
    weather: { temp: '14°C', condition: 'Chilly & Fresh', icon: 'cloud', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Digital payments accepted in main town squares.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No permit needed for Indian nationals.' },
    tags: ['Domestic Havens', 'Snow & Mountains', 'Adventure', 'Family', 'Roadtrips'],
  },
  {
    id: 'dest-ladakh',
    name: 'Leh & Ladakh',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'High altitude desert, mirror-like Pangong Tso, and ancient Buddhist gompas',
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
    startingPrice: 27500,
    bestTimeToVisit: 'May – Sep',
    avgDuration: '6–8 Days',
    rating: 4.96,
    reviewsCount: 3100,
    popularActivities: ['Pangong Tso Blue Lake Camping', 'Khardung La World Highest Motorable Pass', 'Nubra Valley Double-Humped Camel Ride', 'Thiksey & Hemis Monastery Morning Prayers'],
    description: 'The Moonland of India: stark snow peaks, dramatic mountain passes, stargazing under zero light pollution, and profound Buddhist spirituality.',
    weather: { temp: '12°C', condition: 'Sunny & Crisp High Altitude', icon: 'wb_sunny', uvIndex: '8 Very High' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Carry physical cash for remote passes and homestays.' },
    visaProtocol: { title: 'Inner Line Permit (ILP)', summary: 'Online ILP required for Nubra & Pangong, easily arranged in Leh town.' },
    tags: ['Domestic Havens', 'Adventure', 'Biking & Roadtrips', 'Mountains', 'Spirituality'],
  },
  {
    id: 'dest-varanasi',
    name: 'Varanasi',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Spiritual capital of India: sacred Ganges ghats, evening Aarti, and eternal history',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    startingPrice: 11000,
    bestTimeToVisit: 'Oct – Mar',
    avgDuration: '3–4 Days',
    rating: 4.86,
    reviewsCount: 4100,
    popularActivities: ['Dashashwamedh Ghat Evening Ganga Aarti', 'Subah-e-Banaras Sunrise Boat Ride', 'Kashi Vishwanath Corridor Darshan', 'Sarnath Buddhist Stupa Exploration'],
    description: 'One of the world’s oldest continuously inhabited cities where ancient rituals, mystical chants, boat rides along the holy river, and Banarasi silk weave unforgettable memories.',
    weather: { temp: '25°C', condition: 'Mild & Sunny', icon: 'self_improvement', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Seamless UPI payments everywhere from ghat stalls to silk emporiums.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'Standard Indian identification.' },
    tags: ['Domestic Havens', 'Spirituality', 'Culture', 'Heritage', 'Ghats'],
  },
  {
    id: 'dest-sikkim',
    name: 'Sikkim & Gangtok',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Himalayan wonderland: Kanchenjunga panoramas, alpine lakes, and monasteries',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    startingPrice: 19800,
    bestTimeToVisit: 'Mar – May & Oct – Dec',
    avgDuration: '5–6 Days',
    rating: 4.89,
    reviewsCount: 2750,
    popularActivities: ['Tsomgo Lake & Baba Mandir Excursion', 'Nathula Pass Indo-China Border', 'Rumtek Monastery Prayer Bells', 'MG Marg Gangtok Evening Stroll'],
    description: 'India’s first 100% organic state nestled beneath the world’s third-highest peak, filled with vibrant rhododendrons and Buddhist chants.',
    weather: { temp: '15°C', condition: 'Cool Alpine Air', icon: 'landscape', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'UPI widely functional in Gangtok.' },
    visaProtocol: { title: 'Nathula Pass Permit', summary: 'Obtained via authorized local tour operators 24h in advance.' },
    tags: ['Domestic Havens', 'Mountains', 'Nature', 'Honeymoon', 'Buddhist Culture'],
  },
  {
    id: 'dest-rishikesh',
    name: 'Rishikesh & Haridwar',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Yoga capital of the world, adrenaline white-water rapids, and holy riverbanks',
    image: 'https://images.unsplash.com/photo-1600100397608-f010e47c1348?auto=format&fit=crop&w=800&q=80',
    startingPrice: 9500,
    bestTimeToVisit: 'Sep – Nov & Mar – May',
    avgDuration: '3–4 Days',
    rating: 4.84,
    reviewsCount: 4400,
    popularActivities: ['Grade III/IV River Rafting on the Ganges', 'Bungee Jumping at Mohan Chatti (83m)', 'Triveni Ghat Evening Maha Aarti', 'Beatles Ashram Meditation & Murals'],
    description: 'Where Himalayan stillness meets heart-pumping adventure. Experience cliff jumps, riverside camping, cafe culture, and sacred bells.',
    weather: { temp: '24°C', condition: 'Pleasant & Breezy', icon: 'kayaking', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Fast digital payments across all cafes and rafting outfits.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'No visa required.' },
    tags: ['Domestic Havens', 'Adventure', 'Spirituality', 'Weekend Getaway', 'Budget Friendly'],
  },
  {
    id: 'dest-agra',
    name: 'Agra (Taj Mahal)',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'The timeless monument of love, grand Mughal forts, and imperial history',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    startingPrice: 8500,
    bestTimeToVisit: 'Oct – Mar',
    avgDuration: '2–3 Days',
    rating: 4.88,
    reviewsCount: 7800,
    popularActivities: ['Sunrise at the Taj Mahal', 'Agra Fort Royal Chambers Tour', 'Mehtab Bagh Sunset Across Yamuna', 'Fatehpur Sikri Imperial Ruins'],
    description: 'Home to the iconic Wonder of the World. Marvel at flawless white marble, intricate inlay craftsmanship, and world-class heritage.',
    weather: { temp: '26°C', condition: 'Sunny & Pleasant', icon: 'wb_sunny', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'ASI monument tickets booked digitally.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'Open for all visitors.' },
    tags: ['Domestic Havens', 'World Wonder', 'Heritage', 'Short Trip', 'Iconic'],
  },
  {
    id: 'dest-amritsar',
    name: 'Amritsar',
    stateOrCountry: 'India',
    isInternational: false,
    category: 'Domestic Havens',
    tagline: 'Spiritual haven: Golden Temple serenity, Wagah border patriotic roar, and Punjabi cuisine',
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80',
    startingPrice: 9000,
    bestTimeToVisit: 'Oct – Mar',
    avgDuration: '2–3 Days',
    rating: 4.92,
    reviewsCount: 5100,
    popularActivities: ['Golden Temple Harmandir Sahib Night Illuminated Visit', 'Wagah Border Beating Retreat Ceremony', 'Jallianwala Bagh Memorial', 'Authentic Amritsari Kulcha & Lassi Food Trail'],
    description: 'Feel the peace of the world’s largest community kitchen (Langar), witness the border spectacle, and savor legendary North Indian cuisine.',
    weather: { temp: '22°C', condition: 'Pleasant & Cool', icon: 'sunny', uvIndex: '5 Moderate' },
    currencyInfo: { currencyName: 'INR (₹)', rateText: 'Local Currency', note: 'Full digital connectivity.' },
    visaProtocol: { title: 'Domestic Travel', summary: 'Standard ID required.' },
    tags: ['Domestic Havens', 'Spirituality', 'Culinary & Food', 'Patriotism', 'Culture'],
  },

  // ==========================================
  // 5. INTERNATIONAL ICONS (9 DESTINATIONS)
  // ==========================================
  {
    id: 'dest-dubai',
    name: 'Dubai',
    stateOrCountry: 'United Arab Emirates',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Futuristic architecture, desert horizons, and opulent coastal luxury',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    startingPrice: 38400,
    bestTimeToVisit: 'Nov – Mar (Peak winter season)',
    avgDuration: '5–6 Days',
    rating: 4.9,
    reviewsCount: 4210,
    popularActivities: ['Burj Khalifa Observation Deck', 'Desert Safari with Dune Bashing', 'Dubai Marina Luxury Yacht Cruise', 'The Dubai Mall Fountain Show'],
    description: 'Dubai represents the pinnacle of modern architectural marvels, world-class hospitality, tax-free retail therapy, and exhilarating desert adventures nestled alongside the warm Persian Gulf.',
    weather: { temp: '28°C', condition: 'Sunny & Pleasant', icon: 'wb_sunny', uvIndex: '5 Moderate', seaTemp: '26°C' },
    currencyInfo: { currencyName: 'AED (Dirham)', rateText: '1 AED ≈ ₹22.65', note: 'Cards widely accepted everywhere, UPI expanding rapidly across major malls.' },
    visaProtocol: { title: '30-Day Express eVisa', summary: 'Instant 24-48h digital processing for Indian passport holders with confirmed tickets.' },
    tags: ['International Icons', 'Ultra Modern', 'Luxury', 'Shopping', 'Desert Safaris'],
  },
  {
    id: 'dest-japan',
    name: 'Japan (Tokyo, Kyoto & Osaka)',
    stateOrCountry: 'Japan',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Neon cyberpunk metropolises, cherry blossoms, Mount Fuji, and ancient Shinto shrines',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    startingPrice: 110000,
    bestTimeToVisit: 'Mar – May (Cherry Blossom) & Oct – Nov (Autumn Foliage)',
    avgDuration: '7–9 Days',
    rating: 4.96,
    reviewsCount: 3400,
    popularActivities: ['Shinkansen Bullet Train past Mount Fuji', 'Kyoto Fushimi Inari 10,000 Red Torii Gates', 'Shibuya Crossing & Tokyo SkyTree', 'Osaka Dotonbori Street Food Feast'],
    description: 'A mind-bending fusion of centuries-old Zen tradition, polite hospitality, ultra-efficient bullet trains, Michelin ramen, and futuristic innovation.',
    weather: { temp: '17°C', condition: 'Pleasant & Crisp', icon: 'wb_sunny', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'JPY (Japanese Yen)', rateText: '100 JPY ≈ ₹58', note: 'IC transit cards (Suica/Pasmo) on Apple Wallet/Google Pay make payments effortless.' },
    visaProtocol: { title: 'eVisa for Indians', summary: 'Straightforward short-term digital tourist eVisa available online.' },
    tags: ['International Icons', 'Futuristic', 'Shinto Shrines', 'Bullet Trains', 'Culinary & Culture'],
  },
  {
    id: 'dest-usa',
    name: 'United States (New York, California & Vegas)',
    stateOrCountry: 'United States of America',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Times Square neon, Golden Gate Bridge, Grand Canyon majesty, and Hollywood dreams',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
    startingPrice: 175000,
    bestTimeToVisit: 'Apr – Oct',
    avgDuration: '10–14 Days',
    rating: 4.93,
    reviewsCount: 5800,
    popularActivities: ['Statue of Liberty & Times Square Broadway', 'Grand Canyon South Rim Helicopter Tour', 'San Francisco Golden Gate Bridge & Alcatraz', 'Las Vegas Strip Bellagio Fountain Show'],
    description: 'Epic coast-to-coast adventures: world-famous skylines, colossal national parks, world-class entertainment, and global cultural landmarks.',
    weather: { temp: '20°C', condition: 'Clear Skies', icon: 'apartment', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'USD ($)', rateText: '1 USD ≈ ₹86.5', note: 'Apple Pay and contactless cards accepted everywhere.' },
    visaProtocol: { title: 'B1/B2 Tourist Visa', summary: '10-year multiple-entry tourist visa.' },
    tags: ['International Icons', 'Megacities', 'National Parks', 'Entertainment', 'Iconic'],
  },
  {
    id: 'dest-australia',
    name: 'Australia (Sydney & Melbourne)',
    stateOrCountry: 'Australia',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Sydney Opera House, Bondi surfing, Great Barrier Reef, and koala sanctuaries',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
    startingPrice: 138000,
    bestTimeToVisit: 'Oct – Apr (Aussie Summer)',
    avgDuration: '8–10 Days',
    rating: 4.92,
    reviewsCount: 2900,
    popularActivities: ['Sydney Opera House & Harbour Bridge Climb', 'Bondi to Coogee Coastal Cliff Walk', 'Great Barrier Reef Scuba & Snorkel', 'Melbourne Great Ocean Road 12 Apostles'],
    description: 'Golden sunshine, friendly wildlife encounters with kangaroos, vibrant coastal coffee culture, and world-heritage marine marvels.',
    weather: { temp: '26°C', condition: 'Sunny & Coastal', icon: 'sunny', uvIndex: '8 High' },
    currencyInfo: { currencyName: 'AUD ($)', rateText: '1 AUD ≈ ₹56.5', note: '100% cashless friendly across all cities.' },
    visaProtocol: { title: 'Australian Subclass 600 eVisa', summary: 'Completely paperless online biometric tourist visa application.' },
    tags: ['International Icons', 'Wildlife', 'Beaches', 'Harbour Cities', 'Adventure'],
  },
  {
    id: 'dest-newzealand',
    name: 'New Zealand (Queenstown & Auckland)',
    stateOrCountry: 'New Zealand',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Adventure capital of the world, breathtaking Milford Sound fiords, and Middle-earth landscapes',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
    startingPrice: 165000,
    bestTimeToVisit: 'Nov – Apr (NZ Summer)',
    avgDuration: '9–12 Days',
    rating: 4.97,
    reviewsCount: 2200,
    popularActivities: ['Milford Sound Glass-Roof Boat Cruise', 'Queenstown Skyline Gondola & Luge', 'Hobbiton Movie Set Guided Tour in Matamata', 'Waitomo Glowworm Caves Boat Ride'],
    description: 'Pure adrenaline and untouched natural majesty: pristine alpine lakes, glacier valleys, bungy jumping, and epic Lord of the Rings settings.',
    weather: { temp: '21°C', condition: 'Crisp & Pure Mountain Air', icon: 'landscape', uvIndex: '7 High' },
    currencyInfo: { currencyName: 'NZD ($)', rateText: '1 NZD ≈ ₹51.2', note: 'Contactless cards work across the entire country.' },
    visaProtocol: { title: 'Visitor Visa / NZeTA', summary: 'Standard online visitor visa processed via Immigration NZ portal.' },
    tags: ['International Icons', 'Pristine Nature', 'Adrenaline Adventure', 'Fiords', 'Middle Earth'],
  },
  {
    id: 'dest-egypt',
    name: 'Egypt (Cairo & Nile Cruise)',
    stateOrCountry: 'Egypt',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Great Pyramids of Giza, Sphinx mysteries, and luxury 5-star Nile River cruises',
    image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=800&q=80',
    startingPrice: 72000,
    bestTimeToVisit: 'Oct – Apr',
    avgDuration: '6–8 Days',
    rating: 4.88,
    reviewsCount: 2700,
    popularActivities: ['Great Pyramids of Giza & Sphinx Camel Trek', '4-Night 5-Star Nile River Cruise (Luxor to Aswan)', 'Valley of the Kings King Tut Tomb', 'Grand Egyptian Museum Antiquities'],
    description: 'Unravel 5,000 years of civilization: colossal pharaonic temples, mysterious golden sarcophagi, sailing the legendary Nile, and desert vistas.',
    weather: { temp: '26°C', condition: 'Warm & Sunny Desert', icon: 'wb_sunny', uvIndex: '6 Moderate' },
    currencyInfo: { currencyName: 'EGP (Egyptian Pound)', rateText: '1 EGP ≈ ₹1.7', note: 'Very budget friendly. Cash useful for tips and markets.' },
    visaProtocol: { title: 'Egyptian eVisa', summary: 'Simple online tourist eVisa processed in 3-5 days.' },
    tags: ['International Icons', 'Ancient Wonders', 'Nile Cruise', 'Pyramids', 'History'],
  },
  {
    id: 'dest-southafrica',
    name: 'South Africa (Cape Town & Kruger Safari)',
    stateOrCountry: 'South Africa',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Table Mountain cableway, Boulders Beach penguins, and Big Five safari game drives',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
    startingPrice: 128000,
    bestTimeToVisit: 'Nov – Mar',
    avgDuration: '7–9 Days',
    rating: 4.93,
    reviewsCount: 2150,
    popularActivities: ['Table Mountain Rotating Cableway Summit', 'Kruger National Park Open 4x4 Game Safari', 'Cape Point & Boulders Beach African Penguin Colony', 'Stellenbosch Scenic Wine Estate Tour'],
    description: 'Where dramatic ocean cliffs meet the wild African bush. Marvel at lions and elephants, swim with seals, and savor world-famous coastal sunsets.',
    weather: { temp: '25°C', condition: 'Sunny & Coastal', icon: 'pets', uvIndex: '7 High' },
    currencyInfo: { currencyName: 'ZAR (South African Rand)', rateText: '1 ZAR ≈ ₹4.6', note: 'Cards widely accepted across Cape Town.' },
    visaProtocol: { title: 'Standard Visitor Visa', summary: 'Processed via VFS Global.' },
    tags: ['International Icons', 'Big Five Safari', 'Wildlife', 'Table Mountain'],
  },
  {
    id: 'dest-southkorea',
    name: 'South Korea (Seoul & Jeju Island)',
    stateOrCountry: 'South Korea',
    isInternational: true,
    category: 'International Icons',
    tagline: 'K-Pop capital, neon Gangnam streets, imperial palaces, and volcanic Jeju wonders',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80',
    startingPrice: 88000,
    bestTimeToVisit: 'Mar – May & Sep – Nov',
    avgDuration: '6–7 Days',
    rating: 4.9,
    reviewsCount: 2300,
    popularActivities: ['Gyeongbokgung Palace Hanbok Royal Walk', 'N Seoul Tower Sunset Locks of Love', 'Jeju Island Seongsan Ilchulbong Sunrise Peak', 'Myeongdong K-Beauty & Street Food Night Stroll'],
    description: 'Dynamic cultural phenomenon blending historic Joseon dynasty palaces, high-tech subways, skincare shopping, and sensational Korean BBQ.',
    weather: { temp: '16°C', condition: 'Crisp & Sunny', icon: 'wb_sunny', uvIndex: '4 Mild' },
    currencyInfo: { currencyName: 'KRW (South Korean Won)', rateText: '1,000 KRW ≈ ₹62', note: 'T-money transport card and forex credit cards widely used.' },
    visaProtocol: { title: 'Standard Tourist Visa', summary: 'Processed through Korea Visa Application Center (KVAC).' },
    tags: ['International Icons', 'K-Pop & Culture', 'Shopping & Skincare', 'Palaces', 'Clean Cities'],
  },
  {
    id: 'dest-mauritius',
    name: 'Mauritius',
    stateOrCountry: 'Mauritius',
    isInternational: true,
    category: 'International Icons',
    tagline: 'Indian Ocean paradise: Seven Colored Earths, luxury beach resorts, and catamaran sailing',
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    startingPrice: 58000,
    bestTimeToVisit: 'May – Dec',
    avgDuration: '5–6 Days',
    rating: 4.88,
    reviewsCount: 2600,
    popularActivities: ['Ile Aux Cerfs Catamaran Cruise & Parasailing', 'Chamarel Seven Colored Earths & Waterfall', 'Casela Nature Park Walk with Lions', 'Dolphin Encounter in Tamarin Bay'],
    description: 'Warm Indian Ocean waters, sugar cane hills, undersea waterfalls illusion, luxury family beach resorts, and close cultural ties with India.',
    weather: { temp: '27°C', condition: 'Sunny Island Breeze', icon: 'sailing', uvIndex: '7 High', seaTemp: '26°C' },
    currencyInfo: { currencyName: 'MUR (Mauritian Rupee)', rateText: '1 MUR ≈ ₹1.9', note: 'Cards widely accepted.' },
    visaProtocol: { title: 'Free Visa on Arrival', summary: 'Visa-free 60-day tourist entry on arrival for Indian passport holders.' },
    tags: ['International Icons', 'Beaches', 'Catamarans', 'Honeymoon', 'Family Resorts'],
  },
];

export function getTopAttractions(city: string = 'Dubai'): Attraction[] {
  if (city.toLowerCase() === 'dubai') {
    return DUBAI_ATTRACTIONS;
  }
  return DUBAI_ATTRACTIONS;
}
