import { HolidayPackage } from '../types/travel';

export const MOCK_HOLIDAY_PACKAGES: HolidayPackage[] = [
  {
    id: 'pkg-dubai-explorer',
    title: 'Dubai Explorer',
    destination: 'Dubai',
    country: 'United Arab Emirates',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 48999,
    originalPrice: 58500,
    rating: 4.9,
    reviewsCount: 1200,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    description: '4-Star Marina Hotel, Desert Safari with BBQ, Burj Khalifa 124th Floor, and Marina Dhow Cruise.',
    inclusions: ['Roundtrip Flights DEL-DXB', '5 Nights 4-Star Stay', 'Daily Breakfast Buffet', 'Private Tesla Airport Transfers', 'Desert Safari + BBQ Banquet', 'Burj Khalifa 124th Floor Entry'],
    highlights: ['Marina Dhow Dinner Cruise', 'Burj Khalifa Observation Deck', 'Red Dune Bashing & Stargazing', 'Free Dubai Mall Shopping Pass'],
    category: 'international',
    tags: ['Best Seller', 'Flights Included', 'Luxury On Budget'],
    hotelCategory: '4-Star Waterfront Hotel',
    featured: true,
  },
  {
    id: 'pkg-kerala-backwaters',
    title: 'Kerala Backwaters & Munnar',
    destination: 'Munnar & Alleppey',
    country: 'India',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 24500,
    originalPrice: 31000,
    rating: 4.88,
    reviewsCount: 850,
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    description: 'Private Alleppey Houseboat stay, organic Spice Plantation walks, and Munnar hill tea garden tours.',
    inclusions: ['Dedicated Private Sedan Cab', '3N Tea Valley Resort Munnar', '2N Deluxe Alleppey Houseboat', 'All Houseboat Meals (Kerala Feast)', 'Kathakali Dance Show Entry'],
    highlights: ['Tea Museum & Mattupetty Dam', 'Eravikulam National Park (Nilgiri Tahr)', 'Serene Canal Houseboat Cruise', 'Organic Spice Garden Tour'],
    category: 'domestic',
    tags: ['Couples Choice', 'Nature & Serenity', 'Under ₹30k'],
    hotelCategory: 'Resort & Deluxe Houseboat',
    featured: true,
  },
  {
    id: 'pkg-kashmir-paradise',
    title: 'Kashmir Heavenly Valleys',
    destination: 'Srinagar, Gulmarg & Pahalgam',
    country: 'India',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 29500,
    originalPrice: 38000,
    rating: 4.95,
    reviewsCount: 1450,
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
    description: 'Luxury Dal Lake Shikara rides, Gulmarg Gondola Phase 2 snow heights, and Betaab Valley pine forests.',
    inclusions: ['1N Heritage Nigeen Lake Houseboat', '4N Luxury Boutique Resorts', 'All Transfers in Dedicated SUV', 'Gulmarg Gondola Ride Cable Pass', 'Breakfast & Authentic Kashmiri Wazwan Dinners'],
    highlights: ['Sunset Shikara Ride with Kahwa Tea', 'Gondola Ride to Apharwat Peak', 'Pahalgam Aru & Betaab Valley excursion', 'Mughal Gardens of Shalimar & Nishat'],
    category: 'domestic',
    tags: ['Snow & Mountains', 'Trending', 'Under ₹50k'],
    hotelCategory: 'Luxury Houseboat & Boutique Alpine Resort',
    featured: true,
  },
  {
    id: 'pkg-goa-sun-sand',
    title: 'Goa Coastal Serenity & Heritage',
    destination: 'North & South Goa',
    country: 'India',
    durationNights: 4,
    durationDays: 5,
    pricePerPerson: 16500,
    originalPrice: 22000,
    rating: 4.82,
    reviewsCount: 2200,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    description: 'Boutique Portuguese villa stay, Calangute water sports, Old Goa cathedrals, and sunset catamaran.',
    inclusions: ['4N 4-Star Resort with Pool', 'Airport Pickup & Drop', 'Mandovi River Sunset Catamaran Cruise', 'Dudhsagar Waterfall Jeep Safari', 'Complimentary Scooter / Cab Day'],
    highlights: ['Anjuna & Vagator Sunset Beach Clubs', 'Water Sports Package (Jet Ski & Parasailing)', 'UNESCO Basílica of Bom Jesus', 'Spice Farm Lunch Buffet'],
    category: 'domestic',
    tags: ['Beaches', 'Nightlife', 'Under ₹20k'],
    hotelCategory: '4-Star Beach Resort',
    featured: true,
  },
  {
    id: 'pkg-rajasthan-royal',
    title: 'Royal Rajasthan Heritage Trail',
    destination: 'Jaipur, Jodhpur & Udaipur',
    country: 'India',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 28900,
    originalPrice: 36000,
    rating: 4.9,
    reviewsCount: 1800,
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    description: 'Stay in royal heritage havelis, private boat cruise on Lake Pichola, Amber Fort light show, and Mehrangarh fort.',
    inclusions: ['Private Chauffeur-driven AC Sedan', '6N Heritage Palace & Haveli Stays', 'Lake Pichola Sunset Boat Cruise', 'Amber Fort & City Palace Guided Entries', 'Daily Royal Rajasthani Breakfasts'],
    highlights: ['Hawa Mahal & Jantar Mantar', 'Lake Palace View at Sunset', 'Mehrangarh Fort Panorama', 'Chokhi Dhani Cultural Village Dinner'],
    category: 'domestic',
    tags: ['Royal Palaces', 'Heritage', 'Best Value'],
    hotelCategory: 'Heritage Palace Haveli',
    featured: true,
  },
  {
    id: 'pkg-andaman-tropical',
    title: 'Andaman Tropical Island Odyssey',
    destination: 'Port Blair & Havelock',
    country: 'India',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 34500,
    originalPrice: 42000,
    rating: 4.92,
    reviewsCount: 1100,
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    description: 'Radhanagar white sand beach, Makruzz luxury catamaran cruise, introductory scuba diving, and Cellular Jail.',
    inclusions: ['5N Beachfront Luxury Resort', 'Makruzz Premium Cruise Tickets', 'Cellular Jail Light & Sound Entry', 'Introductory Scuba Diving with Photos', 'Daily Breakfast Buffets'],
    highlights: ['Asia Best Beach Radhanagar', 'Elephant Beach Coral Snorkeling', 'Kalapathar Beach Sunrise Walk', 'Chidiya Tapu Sunset Point'],
    category: 'domestic',
    tags: ['Islands & Scuba', 'Couples', 'White Sands'],
    hotelCategory: 'Beachfront Island Resort',
    featured: true,
  },
  {
    id: 'pkg-ladakh-expedition',
    title: 'Leh & Pangong High-Altitude Odyssey',
    destination: 'Leh, Nubra Valley & Pangong Tso',
    country: 'India',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 36000,
    originalPrice: 45000,
    rating: 4.96,
    reviewsCount: 1350,
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
    description: 'Cross Khardung La (world highest motorable pass), camp beside azure Pangong Lake, and ride double-humped camels.',
    inclusions: ['Dedicated 4x4 Scorpio / Innova SUV', '1N Luxury Lakeside Camp at Pangong', '5N Boutique Hotel in Leh & Nubra', 'Inner Line Travel Permits & Oxygen Cylinder', 'All Breakfasts & Dinners'],
    highlights: ['Sunrise over Color-Changing Pangong Tso', 'Khardung La Summit Milestone (18,380 ft)', 'Hunder White Sand Dunes Camel Safari', 'Thiksey & Diskit Giant Buddha Statues'],
    category: 'domestic',
    tags: ['Adventure', 'Mountains', 'Bucket List'],
    hotelCategory: 'Luxury Lake Camp & Boutique Hotel',
    featured: false,
  },
  {
    id: 'pkg-bali-romantic',
    title: 'Bali Romantic Escape',
    destination: 'Bali (Seminyak & Ubud)',
    country: 'Indonesia',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 54000,
    originalPrice: 65000,
    rating: 4.9,
    reviewsCount: 2100,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    description: 'Private Pool Villa in Seminyak, Ubud Jungle Waterfalls tour, Uluwatu sunset temple & romantic beach dinner.',
    inclusions: ['Private Pool Villa 6 Nights', 'Floating Breakfast & Balinese Massage', 'Airport VIP Expedited Pickup', 'Ubud Sacred Monkey Forest & Waterfalls Tour', 'Candlelight Seafood Dinner at Jimbaran Bay'],
    highlights: ['Uluwatu Sunset Clifftop Temple', 'Kanto Lampo & Tibumana Waterfalls', 'Jungle Swing Adventure', 'AI Concierge for Beach Club Access'],
    category: 'honeymoon',
    tags: ['Romantic Highlight', 'Private Villa', 'AI Concierge'],
    hotelCategory: '5-Star Luxury Private Pool Villa',
    featured: true,
  },
  {
    id: 'pkg-singapore-family',
    title: 'Singapore Family Fantasy',
    destination: 'Singapore',
    country: 'Singapore',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 62000,
    originalPrice: 74000,
    rating: 4.9,
    reviewsCount: 980,
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
    description: 'Sentosa Island Express pass, Universal Studios Singapore tickets, Gardens by the Bay, and Night Safari.',
    inclusions: ['Roundtrip Flights Included', '5N 4-Star Orchard Road Hotel', 'Universal Studios Express All-Ride Passes', 'Gardens by the Bay Flower Dome & Cloud Forest', 'Night Safari Tram with Priority Seating'],
    highlights: ['Sentosa Cable Car Experience', 'Marina Bay Sands SkyPark Deck', 'Changi Jewel Light & Vortex Waterfall', 'Kids Free Entry to Science Centre'],
    category: 'family',
    tags: ['Family Favorite', 'All Parks Included', 'Direct Flights'],
    hotelCategory: '4-Star Centrally Located Hotel',
    featured: true,
  },
  {
    id: 'pkg-thailand-islands',
    title: 'Thailand Phuket & Krabi Island Hopping',
    destination: 'Phuket & Krabi',
    country: 'Thailand',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 36500,
    originalPrice: 44000,
    rating: 4.86,
    reviewsCount: 2400,
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80',
    description: 'Phi Phi & Maya Bay speedboat tour, James Bond Island sea kayaking, 4-Star beachfront stay, and Thai street food.',
    inclusions: ['Roundtrip Airfare Included', '5N 4-Star Beachfront Resort', 'Phi Phi & Bamboo Island Speedboat Tour', 'James Bond Island & Sea Canoeing', 'Daily Hot Buffet Breakfasts'],
    highlights: ['Maya Bay The Beach Location', 'Patong Night Market & Bangla Road', 'Big Buddha Phuket Viewpoint', 'Krabi 4-Island Sunset Snorkeling'],
    category: 'international',
    tags: ['Visa-Free Entry', 'Beaches', 'Under ₹40k'],
    hotelCategory: '4-Star Beachfront Resort',
    featured: true,
  },
  {
    id: 'pkg-maldives-luxury',
    title: 'Maldives Overwater Paradise',
    destination: 'Male Atoll',
    country: 'Maldives',
    durationNights: 4,
    durationDays: 5,
    pricePerPerson: 78000,
    originalPrice: 95000,
    rating: 4.97,
    reviewsCount: 1650,
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    description: 'Overwater Villa with direct lagoon access, all-inclusive gourmet meals, speed-boat transfers, and sunset dolphin cruise.',
    inclusions: ['4N Water Villa with Plunge Pool', 'All-Inclusive Dine-Around (Breakfast, Lunch, Dinner & Drinks)', 'Roundtrip Speedboat Island Transfers', 'Sunset Dolphin Watch Cruise', 'Complimentary Snorkeling Equipment'],
    highlights: ['Direct Lagoon Deck Stairway', 'Bioluminescent Beach Stroll', 'Undersea Wine Tasting', 'Couples Spa Ritual Credit'],
    category: 'luxury',
    tags: ['Ultra Luxury', 'Overwater Villa', 'Honeymoon'],
    hotelCategory: '5-Star Overwater Resort',
    featured: true,
  },
  {
    id: 'pkg-vietnam-highlights',
    title: 'Vietnam Ha Long Bay & Golden Bridge',
    destination: 'Hanoi, Da Nang & Ha Long',
    country: 'Vietnam',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 42000,
    originalPrice: 51000,
    rating: 4.91,
    reviewsCount: 1950,
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80',
    description: '5-Star Ha Long Bay overnight cruise with balcony suite, Ba Na Hills Golden Hand bridge, and Hoi An lantern boat.',
    inclusions: ['1N 5-Star Ha Long Luxury Balcony Cruise', '5N 4-Star Boutique Hotels in Hanoi & Hoi An', 'Internal Flight Hanoi to Da Nang', 'Ba Na Hills Cable Car & Golden Bridge Entry', 'All Cruise Meals & City Tour Guides'],
    highlights: ['Ha Long Bay Limestone Cave Kayaking', 'Ba Na Hills Giant Hands Suspension Bridge', 'Hoi An Ancient Lantern River Boat', 'Hanoi Old Quarter Street Food Trail'],
    category: 'international',
    tags: ['Top Trending', 'Amazing Value', 'Cruises'],
    hotelCategory: '5-Star Cruise & Boutique Hotels',
    featured: true,
  },
  {
    id: 'pkg-switzerland-alpine',
    title: 'Swiss Alps & Glacier Express',
    destination: 'Zurich, Lucerne & Interlaken',
    country: 'Switzerland',
    durationNights: 7,
    durationDays: 8,
    pricePerPerson: 135000,
    originalPrice: 155000,
    rating: 4.95,
    reviewsCount: 620,
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    description: 'First-class Swiss Travel Pass, Jungfraujoch Top of Europe, Mount Titlis revolving gondola, and Lake Brienz cruise.',
    inclusions: ['8-Day First Class Swiss Travel Rail Pass', '7 Nights 4-Star Alpine Chalet Hotels', 'Jungfraujoch Mountain Train Ticket', 'Titlis Cliff Walk & Rotair Gondola', 'Daily Gourmet Swiss Buffet Breakfast'],
    highlights: ['Lucerne Chapel Bridge & Lion Monument', 'Interlaken Paragliding Valley View', 'GoldenPass Scenic Express Train', 'Zurich Old Town Chocolate Workshop'],
    category: 'luxury',
    tags: ['Bucket List', 'Pure Luxury', 'Scenic Trains'],
    hotelCategory: '4-Star Alpine Chalet',
    featured: true,
  },
  {
    id: 'pkg-japan-tokyo-kyoto',
    title: 'Japan Cyberpunk & Zen Temples',
    destination: 'Tokyo, Kyoto & Osaka',
    country: 'Japan',
    durationNights: 7,
    durationDays: 8,
    pricePerPerson: 119000,
    originalPrice: 138000,
    rating: 4.96,
    reviewsCount: 880,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'Shinkansen Bullet Train past Mt. Fuji, Fushimi Inari 10,000 torii gates, Shibuya crossing, and Osaka food markets.',
    inclusions: ['7-Day Japan Rail (JR) Bullet Train Pass', '7N 4-Star City Center Hotels', 'Mount Fuji & Hakone Day Trip with Cruise', 'Kyoto Tea Ceremony & Kimono Experience', 'Universal Studios Japan Priority Pass option'],
    highlights: ['Tokyo Shibuya Crossing & TeamLab Planets', 'Fushimi Inari Vermilion Torii Path', 'Dotonbori Street Food Ramen Tasting', 'Nara Park Friendly Deer Encounters'],
    category: 'international',
    tags: ['Cherry Blossom / Autumn', 'Futuristic', 'Shinkansen'],
    hotelCategory: '4-Star Modern Metro Hotel',
    featured: true,
  },
];

export function getHolidayPackages(categoryFilter?: string): HolidayPackage[] {
  if (!categoryFilter || categoryFilter === 'all' || categoryFilter === 'All Destinations') {
    return MOCK_HOLIDAY_PACKAGES;
  }
  if (categoryFilter === 'Top Rated') {
    return [...MOCK_HOLIDAY_PACKAGES].sort((a, b) => b.rating - a.rating);
  }
  if (categoryFilter === 'Under ₹50k') {
    return MOCK_HOLIDAY_PACKAGES.filter((p) => p.pricePerPerson <= 50000);
  }
  if (categoryFilter === 'Domestic India') {
    return MOCK_HOLIDAY_PACKAGES.filter((p) => p.country === 'India');
  }
  if (categoryFilter === 'International') {
    return MOCK_HOLIDAY_PACKAGES.filter((p) => p.country !== 'India');
  }
  return MOCK_HOLIDAY_PACKAGES.filter(
    (p) => p.category.toLowerCase() === categoryFilter.toLowerCase()
  );
}
