import { Hotel } from '../types/travel';

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'ht-millennium-marina',
    name: 'Millennium Place Marina',
    city: 'Dubai',
    location: 'Dubai Marina',
    distanceFromKeyAttraction: '450m to beach & Dubai Marina Mall',
    starRating: 4,
    ratingScore: 9.1,
    ratingLabel: 'Exceptional',
    reviewsCount: 1420,
    pricePerNight: 7800,
    taxesPerNight: 850,
    badge: '4-Star Premium',
    freeCancellation: true,
    breakfastIncluded: true,
    roomType: 'Superior King Room with Marina Skyline View',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDD5Hs0jifYcRVhwpN2SoelJ4_cpcCEzpYiUKX-Mqr24GzdIZJ0dDmP3aL4Mk37Cg8uBAgYlTiA0Cx_Eopo8s5ySjaueOU71reWkJsHLVyfTyVFvZW7gFP2VIJls1zQ-vxhXCvZqE3KBaq5KNQrmGTWuL7tnWDLwH6U5EiGJ_FKGRppfdXxQqyTZB21XYtMq--5JqRFe9GxzAq5V6pYhRJlYAVJ7TZu4Kh33IQWv3EZs7CziOHpz8CMmw',
    amenities: ['Pool', 'Gym', 'Marina view', 'Free WiFi', 'Complimentary Valet', '24h Room Service'],
    description: 'Superb waterfront property with elevated skyline views, rooftop infinity pool, and direct metro link. Walking distance to the JBR beach walk, yacht charters, and cosmopolitan dining.',
    nearbyAttractions: ['Dubai Marina Promenade (100m)', 'JBR The Beach (450m)', 'Ain Dubai (1.8km)', 'Skydive Dubai (2.2km)'],
  },
  {
    id: 'ht-rove-downtown',
    name: 'Rove Downtown',
    city: 'Dubai',
    location: 'Downtown Dubai',
    distanceFromKeyAttraction: 'Walk to Dubai Mall & Burj Khalifa',
    starRating: 3,
    ratingScore: 9.4,
    ratingLabel: 'Superb',
    reviewsCount: 3890,
    pricePerNight: 5200,
    taxesPerNight: 600,
    badge: '3-Star Boutique',
    freeCancellation: true,
    breakfastIncluded: false,
    roomType: 'Rover Room with Burj Khalifa View',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAoP7T7yi0FQZqpk2R2aRJXMWxcv_4QW32wFDTWdBcAX2U6bBAJHoWltPUnzJ6_uk4dOpT9AYB5YCqiN_sB9Crjya6ghtJd0UXLPs7Sn25-zMeNv_4Lj5P6N2MQrouiFHIgmN2cwS1RxbN3vFZaoMy0uhNkWJjo41zRBJueM1RtmlKU3-JtL-vczGAiI-_wpAz_U3rSuiZrWKAC5vvPJgSzIf7jy1IleT__hUdinI-7j9VhZLj9mGkbjg',
    amenities: ['Burj Khalifa View', 'Free Cancel', 'Free WiFi', 'Daily Shuttle', '24h Gym', 'Co-working Pods', 'Reel Boutique Cinema'],
    description: 'Trendy hub with direct views of Burj Khalifa, 24h gym, private in-house cinema room, and salt-water pool. Exceptional central location adjacent to The Dubai Mall and Downtown boulevard.',
    nearbyAttractions: ['The Dubai Mall (400m)', 'Burj Khalifa Observation Deck (600m)', 'Dubai Opera (900m)', 'Museum of the Future (3km)'],
  },
  {
    id: 'ht-atlantis-the-palm',
    name: 'Atlantis, The Palm',
    city: 'Dubai',
    location: 'Palm Jumeirah',
    distanceFromKeyAttraction: 'Palm Jumeirah Crescent Frontline',
    starRating: 5,
    ratingScore: 9.6,
    ratingLabel: 'Iconic',
    reviewsCount: 5120,
    pricePerNight: 24000,
    taxesPerNight: 2800,
    badge: '5-Star Luxury',
    freeCancellation: true,
    breakfastIncluded: true,
    roomType: 'Ocean King Suite with Arabian Gulf Panorama',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmWWpAVUz_UmEpniuGXwqxDSjtlwUBFU63D7GRpC4sD8rKzFxjvoAA-YhjwOmrwpZFZlWvTXi4RrvZ1KYpwr8S1VMm4aiaZcwyxCoqsbjkjTDyXQTHvFSzjNVtBIMwQhUk0zMXiSX8Cp4DBfl6pgKQ4QiDVOt9dLAjgE8SP3VwvIWtT-0wBQ6m517ktiU4qLRZ3r_HgwygHur9YZVsRDeR8pGU1B8LHLHpxqB4vQL8grDn9K_SXvXXNw',
    amenities: ['Free Aquaventure Access', '23 Restaurants', 'Private Beach', 'Lost Chambers Aquarium', 'ShuiQi Luxury Spa', 'Helipad Access'],
    description: 'World-famous destination resort featuring private beach, giant aquarium, and complimentary daily access to Aquaventure Waterpark. Home to Michelin-starred celebrity restaurants including Nobu & Gordon Ramsay.',
    nearbyAttractions: ['Aquaventure Waterpark (On-site)', 'The Lost Chambers (On-site)', 'The View at The Palm (4.5km)', 'Nakheel Mall (4km)'],
  },
  {
    id: 'ht-address-sky-view',
    name: 'Address Sky View',
    city: 'Dubai',
    location: 'Downtown Dubai',
    distanceFromKeyAttraction: 'Connected to Metro & Dubai Mall',
    starRating: 5,
    ratingScore: 9.7,
    ratingLabel: 'World Class',
    reviewsCount: 2890,
    pricePerNight: 21500,
    taxesPerNight: 2500,
    badge: '5-Star Luxury',
    freeCancellation: true,
    breakfastIncluded: true,
    roomType: 'Panoramic Sky Suite with Twin Towers Infinity Bridge',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAqfpZFG6ToIybrhn-v-0Wrq5a-_4paL8JciJ6ehUhzZpgJLpTZHbyfv7T-h0pi5BzmSeog6E3s4lhz-d4CJ0uS2eNCJ7fEeM7Oa8Kn2OqWI7BV7MNMoogiOH9ttzCmgRoyFUeFgwWiUwKwHTaJfEULSAQaxCsfS1pt9g5uIq-k2CQYK5-WTpmGYaQU-a-sK-RgEK3TkbXmh2KaOwOlRD6J3uewG8gFZk-tqXECcl_Rlwtg64HNyNMU1A',
    amenities: ['Twin Infinity Pools', 'Sky Bridge Walk', 'Burj Khalifa View', 'Full Spa', '5 Fine Dining Outlets'],
    description: 'Architectural twin tower wonder connected by a sky bridge featuring a 70m infinity pool peering over Burj Khalifa. Unmatched luxury at the apex of Downtown Dubai.',
    nearbyAttractions: ['Burj Khalifa (350m)', 'Dubai Mall (250m)', 'City Walk (1.5km)'],
  },
  {
    id: 'ht-al-seef-heritage',
    name: 'Al Seef Heritage Hotel Curio',
    city: 'Dubai',
    location: 'Deira',
    distanceFromKeyAttraction: 'Historic Dubai Creek Banks',
    starRating: 4,
    ratingScore: 9.2,
    ratingLabel: 'Heritage Gem',
    reviewsCount: 1180,
    pricePerNight: 6400,
    taxesPerNight: 750,
    badge: 'Boutique Heritage',
    freeCancellation: true,
    breakfastIncluded: true,
    roomType: 'Traditional Arabic Souk View Chamber',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAOGDOj8Ww5cj-V6IZoS2PzDoD-BFF0g1COtICv7vbEiXWxbsCtkXG874ISgNQLxHYF7X_DcfCkUbFzYNbb2hTT_oTP5pfuh7RMIUshjoiCxPEI7X--7GUD0Y3-KUQZGl4je2vQwkRpznJb0jNcOm780bJkg7NVIaGWDONpeav0-sZLJAwiqENv-IGe-EpEEKcre5eIqOpLiJZVnH2VEQaACUXKfsBnVNqvPwSI5TXOjlHmYESMwEo6g',
    amenities: ['Creek Waterfront', 'Abra Boat Station', 'Traditional Souk', 'Organic Breakfast', 'Cultural Tours'],
    description: 'Immerse in Dubai’s historic roots along the shimmering Dubai Creek. Wind towers, sandstone pathways, and rustic luxury with 5-star comforts.',
    nearbyAttractions: ['Dubai Creek Souks (100m)', 'Dubai Museum (800m)', 'Al Fahidi Historical District (600m)'],
  },
];

export function getHotels(city: string = 'Dubai', areaFilter?: string): Hotel[] {
  let list = MOCK_HOTELS.filter((h) => h.city.toLowerCase() === city.toLowerCase() || city.toLowerCase() === 'all');
  if (areaFilter && areaFilter !== 'All Stays' && areaFilter !== 'all') {
    list = list.filter((h) => h.location.toLowerCase().includes(areaFilter.toLowerCase()));
  }
  return list;
}
